name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    strategy:
      matrix:
        java: ["8"]
        os: ["ubuntu-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Setup JDK ${{ matrix.java }}"
        uses: "actions/setup-java@v3"
        with:
          distribution: 'zulu'
          java-version: "${{ matrix.java }}"
      - name: "Cache Gradle"
        uses: "actions/cache@v3"
        with:
          path: |
            "~/.gradle/caches"
            "~/.gradle/wrapper"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            "${{ runner.os }}-gradle-"
      - name: "Cache Local Maven Repository"
        uses: "actions/cache@v3"
        with:
          path: "~/.m2/repository"
          key: "${{ runner.os }}-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            "${{ runner.os }}-${{ matrix.java }}-maven-"
      - name: "Cache BuildTools Decompiled Code"
        uses: "actions/cache@v3"
        with:
          path: "$GITHUB_WORKSPACE/work"
          key: "${{ runner.os }}-buildtools"
          restore-keys: |
            "${{ runner.os }}-buildtools"
      - name: "Test Enviornment"
        run: "echo $GITHUB_WORKSPACE"
      - name: "Download BuildTools"
        run: "wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
      - name: "Run BuildTools"
        run: "java -jar BuildTools.jar --rev 1.12.2"
      - name: "Clean Build"
        run: "./gradlew clean assemble build"
      - name: Writing version
        run: |
          echo "release_version=$(cat ./version.txt)" >> $GITHUB_ENV
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Upload api artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "fawe-api"
          path: ./mvn/com/boydti/fawe-api/
      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "FastWorldEdit-${{ env.release_version }}"
          path: ./target/